name: armadillo-docs
channels:
  - conda-forge
dependencies:
  - MDAnalysis
  - numpy
  - networkx
  - itertools
  - nglview
  - matplotlib
  - seaborn
  - plotly
  

  - sphinx

  - sphinx_rtd_theme

